### ISSUE TITLE
Make Home - page responsive

### ISSUE THREAD

**Issue by Aniumbott** [Aniumbott/SHOWDOWN#1]
Make the home page Responsive. Also open for suggestions or ideas.

Don't forget to star this repo and follow. 👍

**Comment by AnkurRajneta** [comment]
I am interested can I try this

**Comment by Aniumbott** [comment]
Sure go ahead.

**Comment by nitin-pandita** [comment]
can I this project . If you can assign I will get started with it

**Comment by Aniumbott** [comment]
Ok, you can start but make sure to create a separate branch..

**Comment by Aniumbott** [comment]
@nitin-pandita go ahead.

**Comment by atharvakanse** [comment]
Hello @Aniumbott , I would like to work on it. Could you assign it to me?
