### ISSUE TITLE
Disable empty todo item from getting added into the todos list

### ISSUE THREAD

**Issue by Aashishkushwaha** [Aniumbott/SHOWDOWN#2]
Hi @Aniumbott, Currently we can add the todo item without any text. Ideally this should not happen & we need to prevent this.
If you allow I can fix this issue.
Also please add Hactoberfest label to this issue.

**Comment by Aniumbott** [comment]
yeah sure, go ahead.

**Comment by Aniumbott** [comment]
Can you add this issue to the this [repo](https://github.com/Aniumbott/Todo-List.git) 😅
